server:
  port: 4000
  servlet.context-path: /api

spring:
  jpa.hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:${DB_MAIN_PORT}/${DB_MAIN_DB}
    username: ${DB_MAIN_USERNAME}
    password: ${DB_MAIN_PASSWORD}
  flyway:
    enabled: true
    baselineOnMigrate: true
  security:
    oauth2:
      client:
        registration.keycloak:
          client-id: munchies-client
          authorization-grant-type: authorization_code
          scope: openid
        provider.keycloak:
          issuer-uri: http://localhost:${KEYCLOAK_PORT}/realms/${KEYCLOAK_REALM}
          user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:${KEYCLOAK_PORT}/realms/${KEYCLOAK_REALM}

springdoc:
  api-docs.path: /docs
  swagger-ui.path: /docs.html

values:
  swagger:
    doc: ${springdoc.api-docs.path}/**
    ui: ${springdoc.swagger-ui.path}
    ui-all: /swagger-ui/**