server:
  port: 9000

spring:
  jpa.hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/munchies
    username: admin
    password: admin
  flyway:
    enabled: true
    baselineOnMigrate: true
  security:
    oauth2:
      client:
        registration.keycloak:
          client-id: munchies-client
          authorization-grant-type: authorization_code
          scope: openid
        provider.keycloak:
          issuer-uri: http://localhost:8080/realms/munchies
          user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/munchies
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

springdoc:
  api-docs.path: /docs
  swagger-ui.path: /docs.html

values:
  swagger:
    doc: ${springdoc.api-docs.path}/**
    ui: ${springdoc.swagger-ui.path}
    ui-all: /swagger-ui/**
  rabbitmq:
    queue: statistic